### PR TITLE
Add WebTorrent Desktop; better WebTorrent version parsing

### PR DESCRIPTION
**Pull request by feross**
- Added the new peer ID for WebTorrent Desktop (WD).
- Support parsing the WebTorrent version correctly.

### CODE REVIEW

**Comment by feross** [comment]
@fisch0920 What do you think?

**Comment by feross** [comment]
@fisch0920 Any chance you review this or add me to GitHub/npm so I can publish a new version?

**Comment by fisch0920** [comment]
Looks good; just added you as a collaborator.

Thanks, Feross!

**Comment by feross** [comment]
Thanks Travis!

**Pull request merged**
